### ISSUE TITLE
Enable licence only for specific post type

### ISSUE THREAD

**Issue by benhartwich** [gnotaras/wordpress-creative-commons-configurator#13]
Hi,

how can I enable licence module only for specifc post types?

Regards,

**Comment by gnotaras** [comment]
Hello Ben,

Currently this can be done by excluding unsupported post types.

For example, to only add licensing information to `page` and `attachment` post types, the following should do the trick:

```php
function bccl_force_exclude_licensing($default, $post) {
    $post_type = get_post_type($post);
    if ( $post_type === false ) {
        return $default;
    }
    // Set supported post types
    $supported_types = array('page', 'attachment');
    // Exclude not supported post types
    if ( ! in_array($post_type, $supported_types) ) {
        return true;
    }
    return $default;
}
add_filter('bccl_exclude_license', 'bccl_force_exclude_licensing', 10, 2);
```

However, this can be inconsistent with the plugin settings, which are not very detailed about the post types. Currently, in the settings there are options for posts, pages and attachments. Posts cover custom post types as well.

I plan to work on this again in the future, so I'm going to keep this issue open for a while.

Kind Regards,
George

**Comment by benhartwich** [comment]
Hi,

thanks. The code works. It would be great to select post types and all other types at settings page!

**Comment by gnotaras** [comment]
This is actually in the todo list, but haven't found the time to do it yet. I'll try to implement it soon!

George

**Comment by gnotaras** [comment]
Since I've added this issue in my bug tracker, I'll close this one. Thanks for your feedback.
