### ISSUE TITLE
SSL connection to creative commons.org required

### ISSUE THREAD

**Issue by evamarie42** [gnotaras/wordpress-creative-commons-configurator#7]
Hi,

just noticed that the plugin creates a reference to 'http://creativecommons.org/licenses/by-sa/4.0/'. On my site (https://different-so-what.info) I use SSL and the green logo disappears if I activate the plugin. I fixed it manually the last time, but it would be god if you will fix it in source code.

Thanks,
Eva

**Comment by gnotaras** [comment]
Hi Eva,

Of course the protocol that is used in the license deed URLs needs to be fixed and set to `https`. Thanks for pointing it out! Moreover, linking to the license pages on creativecommons.org using `https` is always a good idea for site verification purposes.

Also, thank you very much for donating to the project! This is much appreciated.

I'll try to make a release containing the fix soon.

Kind Regards,
George

**Comment by gnotaras** [comment]
Hi Eva,

Just released a new version which adds this enhancement. Thanks for your feedback and contribution.

Kind Regards,
George
